const db = require("./connection");
const { Departments, Users } = require("../models");

db.once("open", async () => {
  await Departments.deleteMany();

  const DepartmentList = await Departments.insertMany([
    { name: "Advertising" },
    { name: "HR" },
    { name: "Finance" },
    { name: "Legal" },
  ]);

  console.log("depts seeded");

  await Users.deleteMany();

  const userList = await Users.insertMany([
    {
      name: "Clark Kent",
      email: "Clark.Kent@p3ltd.com",
      employeeID: 10001,
      zoomMeetingID: 4575393480,
      manager: "Perry White",
      organization: "Project 3 LTD",
      department: "Advertising",
      team: "Digital",
      title: "Digital Marketer",
      startDate: "11/11/2011",
      salary: 90000,
      profileBio:
        "Born in a different country, able to jump suspiciously high.",
      rank: 3,
      password: "S0uperman",
    },
    {
      name: "Lois Lane",
      email: "Lois.Lane@p3ltd.com",
      employeeID: 10002,
      zoomMeetingID: 4575393480,
      manager: "Perry White",
      organization: "Project 3 LTD",
      department: "Advertising",
      team: "Digital",
      title: "Social Media Strategist",
      startDate: "3/10/10",
      salary: 100000,
      profileBio:
        "Award winning employee, enjoy spending time with people from out of town",
      rank: 3,
      password: "I<3superman",
    },
    {
      name: "Perry White",
      email: "Perry.White@p3ltd.com",
      employeeID: 10003,
      zoomMeetingID: 4575393480,
      manager: "Dominic Toretto",
      organization: "Project 3 LTD",
      department: "Advertising",
      team: "Digital",
      title: "Brand Manager",
      startDate: "4/30/04",
      salary: 130000,
      profileBio: "enjoys a good cigar",
      rank: 2,
      password: "0ldngrumpy",
    },
    {
      name: "Dominic Toretto",
      email: "Dominic.Toretto@p3ltd.com",
      employeeID: 10000,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "Advertising",
      team: "Marketing",
      title: "CEO",
      startDate: "1/29/01",
      salary: 300000,
      profileBio: "I like cars...and family",
      rank: 1,
      password: "Familia",
    },
    {
      name: "Tony Stark",
      email: "Tony.Stark@p3ltd.com",
      employeeID: 20004,
      zoomMeetingID: 4575393480,
      manager: "Nick Fury",
      organization: "Project 3 LTD",
      department: "Finance",
      team: "Accounting",
      title: "Accountant",
      startDate: "6/21/16",
      salary: 89999,
      profileBio: "I have a lot of suits",
      rank: 3,
      password: "TopGun",
    },
    {
      name: "Pepper Potts",
      email: "Pepper.Potts@p3ltd.com",
      employeeID: 20005,
      zoomMeetingID: 4575393480,
      manager: "Nick Fury",
      organization: "Project 3 LTD",
      department: "Finance",
      team: "Accounting",
      title: "Executive Assistant",
      startDate: "5/25/18",
      salary: 90000,
      profileBio: "I Was Having Twelve Percent Of A Moment.",
      rank: 3,
      password: "ir0nman",
    },
    {
      name: "Nick Fury",
      email: "Nick.Fury@p3ltd.com",
      employeeID: 20001,
      zoomMeetingID: 4575393480,
      manager: "Dominic Toretto",
      organization: "Project 3 LTD",
      department: "Finance",
      team: "Accounting",
      title: "CMA",
      startDate: "9/9/19",
      salary: 150000,
      profileBio: "I hate snakes...especially on planes.",
      rank: 2,
      password: "R0yalwithcheese",
    },
    {
      name: "Elle Woods",
      email: "Elle.Woods@p3ltd.com",
      employeeID: 20000,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "Legal",
      team: "HR",
      title: "Director of HR-Legal",
      startDate: "5/5/05",
      salary: 400000,
      profileBio: "Naturally blonde",
      rank: 1,
      password: "P1nkisthebest",
    },
    {
      Name: "Jack Kirby",
      email: "JK1950@p3ltd.com",
      employeeID: 31000,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "HR",
      team: "HR",
      title: "Employee",
      startDate: "1/24/02",
      salary: 250000,
      profileBio: "i helped build marvel",
      rank: 2,
      password: "Marvel",
    },
    {
      Name: "spongebob",
      email: "jellyfish@p3ltd.com",
      employeeID: 31040,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "HR",
      team: "HR",
      title: "Employee",
      startDate: "5/4/98",
      salary: 150000,
      profileBio: "i love krabby patties",
      rank: 3,
      password: "Krusty",
    },
    {
      Name: "Bob",
      email: "Build@p3ltd.com",
      employeeID: 30057,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "HR",
      team: "HR",
      title: "Employee",
      startDate: "7/2/01",
      salary: 200000,
      profileBio: "yes we can",
      rank: 3,
      password: "Marvel",
    },
    {
      Name: "Tommy Jarvis",
      email: "TJ45@p3ltd.com",
      employeeID: 41000,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "Legal",
      team: "Legal",
      title: "Employee",
      startDate: "9/25/88",
      salary: 100000,
      profileBio: "It’s corn",
      rank: 2,
      password: "Green",
    },
    {
      Name: "Rick Grimes",
      email: "TWD13@p3ltd.com",
      employeeID: 1000,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "Legal",
      team: "Legal",
      title: "Employee",
      startDate: "7/6/83",
      salary: 200000,
      profileBio: "We are the walking dead",
      rank: 3,
      password: "Carl",
    },
    {
      Name: "luke skywalker",
      email: "Jedi0@p3ltd.com",
      employeeID: 41020,
      zoomMeetingID: 4575393480,
      manager: "",
      organization: "Project 3 LTD",
      department: "Legal",
      team: "Legal",
      title: "Employee",
      startDate: "3/11/90",
      salary: 250000,
      profileBio: "That’s not true that imposible",
      rank: 3,
      password: "Light side",
    },
  ]);
});
